### ISSUE TITLE
Flickering

### ISSUE THREAD

**Issue by anuscleaner** [lukeleppan/better-word-count#1]
The word count text does a flickering effect depending on the number of notes I've opened since running Obsidian. It flashes between the different word counts for the notes I've been opening.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/59588053/98661641-b20ecd80-2381-11eb-9410-b2d8feb34f00.gif)

Have wanted this feature in Obsidian in a while and am glad there's finally an option, so thank you for making it! Hoping for further improvement :)

**Comment by lukeleppan** [comment]
Yes, thank you. I tested everything except switching between files. I will have a fix as soon as possible!

**Comment by lukeleppan** [comment]
Problem solved please update the plugin
