### ISSUE TITLE
Feature request: Daily word count

### ISSUE THREAD

**Issue by aknighty74** [lukeleppan/better-word-count#11]
There's already a plugin that does this but it has a serious bug, it deletes all the word count history. 

The addon in question is dhruvik7's https://github.com/dhruvik7/obsidian-daily-stats/issues but he hasn't updated the addon or try to solve the issues for >3 months.

**Comment by lukeleppan** [comment]
I originally wanted to implemented something like that but when that plugin came out I decided against it. 

However, now that he has stopped work on it, I will take a look. Quite busy at the moment so it might take about a month before I release anything. I'll start with the basic stat each day. Then I'll add history. Then someway to view it. Maybe the plugin can collect other stats. Generate a graph of the number of files in your vault over time? Could be quite powerful.

**Comment by lukeleppan** [comment]
Yeah I'm thinking something similar to that. Except more statistics about your obsidian vault. Theoretically there would be a view where you can take a look at your vault progress open time. Some sort of way to see your daily progress overtime.

**Comment by lukeleppan** [comment]
Yeah I'm thinking something similar to that. Except more statistics about your obsidian vault. Theoretically there would be a view where you can take a look at your vault progress open time. Some sort of way to see your daily progress overtime.

**Comment by lukeleppan** [comment]
> There's already a plugin that does this but it has a serious bug, it deletes all the word count history. 
> 
> The addon in question is dhruvik7's https://github.com/dhruvik7/obsidian-daily-stats/issues but he hasn't updated the addon or try to solve the issues for >3 months.

Just letting you know that I haven't forgotten about you and I'm work on this at the moment. Should have an update out probably by the end of the week that will start storing your daily vault statistics. A display of these stats will come later.

**Comment by aknighty74** [comment]
Great news, I'll keep checking the update community addons button every day. And I'm not the only one excited for this update that's for sure. This feature will be a must for every obsidian productivity user, that means almost everyone. Thanks for the update.

**Comment by lukeleppan** [comment]
Update is out!
