### ISSUE TITLE
[BUG] Error Occurs on Chinese Word Counting

### ISSUE THREAD

**Issue by Quorafind** [lukeleppan/better-word-count#12]
I have near 34 words in a note, and Obsidian word counts works well, however, better word count only counts it to 4

![image](https://user-images.githubusercontent.com/13215013/120574937-c536d700-c452-11eb-9c9d-3f82c69ed198.png)

And here is what I wrote in it, you can use it to test if you want.

```
测试
测试
测试
测试
测试
测试
测试我的测试，这是我的测试，这是我的测试
```

**Comment by gblakehl** [comment]
The problem is that the regex for the non-space-breaking words need to be case-sensitive. Replacing line 195 with the lower example (adding brackets and the single match} should fix the issue.

```
var nonSpaceDelimitedWords = /\u3041-\u3096\u309D-\u309F\u30A1-\u30FA\u30FC-\u30FF\u4E00-\u9FD5/
        .source;
```
needs to be...

```
var nonSpaceDelimitedWords = /[\u3041-\u3096\u309D-\u309F\u30A1-\u30FA\u30FC-\u30FF\u4E00-\u9FD5]{1}/
        .source;
```

**Comment by lukeleppan** [comment]
Thank you to the both of you. I will publish an update within the next 24 hours. Keep an eye out.
