### ISSUE TITLE
Feature request: ignore comment

### ISSUE THREAD

**Issue by lammersma** [lukeleppan/better-word-count#13]
Obsidian allows comments. 

Under normal circumstances, I don't want to count these in my word count. Just as formatting is not counted either; ## does not count as a word. Strange that --- is counted, also in Obsidian.

Would be nice to have this as a setting: 
- count or ignore comments
- count or ignore MD stuff
- count or ignore yaml

**Comment by lukeleppan** [comment]
I will look into it thank you👍

**Comment by nomad101** [comment]
Hi, I'm aware the plugin in being rewritten. At the moment I'm using v0.77 with legacy editor. I noticed that the 'Don't count comments' feature displays the correct number of words when displaying {word_count}, i.e. it excludes counting comments. But for {words_today} oddly, it still counts any new comments. 

Is there a quick fix for this? Thanks. 
(I tried looking at the main.js file, but my coding knowledge is too limited).
