### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by NicholasMamo** [lukeleppan/better-word-count#14]
Hi! Coincidentally I just updated to Better Word Count 0.7.2 (I think I was on 0.6.1 before) and I noticed that CPU usage spiked and remained between 100% or 300%; normally, CPU usage is no higher than 50%. The issue goes away when I disable the plugin, so I imagine the problem must have something to do with the latest version.

**Comment by lukeleppan** [comment]
Dang... Let me take a look. Hopefully just an issue with the latest bugfix...

**Comment by lukeleppan** [comment]
Wow that is bad 😬

**Comment by NicholasMamo** [comment]
I think it has something to do with collecting stats. The set up is default, but when I enable stat collection, CPU usage spikes. CPU usage remains high until I turn off stats and restart Obsidian.

**Comment by lukeleppan** [comment]
Ah yes I think it has to do with stat collection.

**Comment by lukeleppan** [comment]
Ok released a new update with some optimizations...
After some testing I can't tell any difference between CPU usage with the plugin activated and not.
I will keep this open for now if issue isn't fixed for you.

**Comment by NicholasMamo** [comment]
Updated the plugin, restarted Obsidian and the issue seems to have gone away. I'll test it properly again tomorrow though. Thank you for the quick fix!

**Comment by NicholasMamo** [comment]
Sadly, the problem hasn't been fixed. I ran the profiler (or whatever it's called, from the Performance tab) from the Dev Tools, and it really does seem like it's this plugin that's hogging CPU (see image below). I noticed that CPU spikes on the minute (so on 12:26:00, 12:27:00, and so on), and lasts about half a minute (but I have a large vault). After disabling statistics, I did not observe the problem again.

![image](https://user-images.githubusercontent.com/24480072/125272545-431cb680-e30c-11eb-9681-8df971fc26f8.png)

**Comment by lukeleppan** [comment]
Ok this is interesting. The plugin stores the total word count every 60 seconds. Just how large is the vault?

**Comment by NicholasMamo** [comment]
I have around 400 files and some 300 PDFs, so not in the thousands, but pretty large.

I updated to the plugin's latest version, and CPU usage spiked immediately (like it was counting words). Then, I turned on statistics and CPU spiked every minute, as before.

Regarding your last reply, do you mean that the plugin, by design, counts all words every minute?

**Comment by lukeleppan** [comment]
For now yes. It was a quick and dirty implementation of the total count but I have a few plans to gather the total word count more efficiently. Maybe by literally storing each file's word count and when it's modify only recounting that file🤔. But I won't really be able to work on the plugin over the next couple. So if not tonight, in the next few days.

**Comment by NicholasMamo** [comment]
No problem at all. I was only toying with the settings and decided to toggle that one—I can live without the feature, but I thought I'd let you know. Thanks all the same for your work on this plugin!

**Comment by aknighty74** [comment]
That's weird. I don't have any problems with the statistics collection feature and must say I have a pretty ancient pc. Windows don't show any kind of spikes and I generally work with 2 vaults and other programs at the same time. In my primary vault I only have 186 files so far though.

The settings I currently have for notes:
![Obsidian_R7ZNEHrrUx](https://user-images.githubusercontent.com/43855619/125497430-904f4930-dbdb-4f60-b57e-7004455db3f5.png)

Common word count:

![TH7pfgrtEx](https://user-images.githubusercontent.com/43855619/125497790-63d6cca0-bb5f-4598-ae16-77bb035b1197.png)

Alternative/general word count:

![LnzZLOR7qq](https://user-images.githubusercontent.com/43855619/125498395-abda58a9-d0d7-4343-bc07-6319366861f6.png)

However, before modifiying it like this I didn't notice any CPU-related problems either.

**Comment by lukeleppan** [comment]
@NicholasMamo Please update and check your performance. Hopefully there is an improvement.

**Comment by lukeleppan** [comment]
Please open a new issue if the issue has not been solved.
