### ISSUE TITLE
Status bar templates showing incorrect results 

### ISSUE THREAD

**Issue by OliverBalfour** [lukeleppan/better-word-count#15]
I'm using 0.7.3.

When I have no files open, or I've got a non markdown pane (eg a graph view or image or PDF), in the past the plugin would show me the total files and words across my vault.

Now it shows me `files files total_words words total_characters characters` in the status bar. The 'alternative status bar text' template string in the settings is the default and has `{}` in the right places. When I have a markdown file open the word count is correct

**Comment by lukeleppan** [comment]
Oh sorry default settings must be broken.

Go into the settings and change the alt text to `{file_count} files {total_word_count} words {total_character_count} characters` should fix.

**Comment by lukeleppan** [comment]
That should fix the default settings.... Sorry for the inconvenience.

**Comment by OliverBalfour** [comment]
Thanks for the quick fix, it's improved. However, after updating and correcting the alt text to `{file_count} files {total_word_count} words {total_character_count} characters` I get this:

![image](https://user-images.githubusercontent.com/11626018/125275168-07a4db00-e352-11eb-8933-2ff234fc815a.png)

For reference, 0.6.2 displayed the total word count as ~235,000

**Comment by lukeleppan** [comment]
Hmm give it 60 seconds and reopen it?

**Comment by lukeleppan** [comment]
Ok I've found the issue.

**Comment by OliverBalfour** [comment]
Thanks. It's working a bit better now, but now it's showing a figure which is too high:

![image](https://user-images.githubusercontent.com/11626018/125293586-e4d0f180-e366-11eb-8a1d-a76b4cc5ef2c.png)

I tried deleting the `.vault-stats` file and relaunching, and the default settings still display a number 10x higher than it should be.

**Comment by lukeleppan** [comment]
I can't see that image. It may be that the word count algorithm has changed since you last checked or may be it is showing the character count?

**Comment by OliverBalfour** [comment]
Here's another copy:

![image](https://user-images.githubusercontent.com/11626018/125387320-0c64a000-e3e1-11eb-907c-12596e0273b1.png)

For reference it says `949 files 3065340 words 15631393 characters`

My vault is ~1000 files, maybe 950 markdown. It has maybe 240,000 words and perhaps 10x that many characters?

I wouldn't bat an eye if the word count was off by <5%, but it's off by >10 times so something's definitely not right.

Thanks for all the quick support by the way, much appreciated!

**Comment by lukeleppan** [comment]
I am assuming the issue has been solved.

**Comment by OliverBalfour** [comment]
Just updated and yes, works like a charm! Thank you!
