### ISSUE TITLE
Resource intensivity

### ISSUE THREAD

**Issue by lishid** [lukeleppan/better-word-count#16]
Got a few reports on this plugin consuming CPU cycles (similar to #14 )

A quick investigation leads to these few lines:
https://github.com/lukeleppan/better-word-count/blob/664cd4e4eda3d2a0074f582a3d9e904ea577f083/src/data/collector.ts#L20

I believe you need to filter for `file.extension === 'md'`, or otherwise you'll be reading every single file into memory, including attachments and unsupported files.

Same for getTotalCharacterCount and getTotalSentenceCount.

**Comment by lishid** [comment]
So this really depends on the user's vault setup - if you have large media files, this could really blow up the computation as well as the RAM usage (because you're using cachedRead on media files, reading them as UTF8 strings).

**Comment by WhiteNoiseDev** [comment]
Also, if I don't use "Collect Statistics", why all the files are being read on startup?

**Comment by lukeleppan** [comment]
> So this really depends on the user's vault setup - if you have large media files, this could really blow up the computation as well as the RAM usage (because you're using cachedRead on media files, reading them as UTF8 strings).

Ohh I wasn't aware that `.getFiles()` got **all** the files. That explains the large total word counts as well. Thank you!
