### ISSUE TITLE
Failure to load resource

### ISSUE THREAD

**Issue by chetachiezikeuzor** [lukeleppan/better-word-count#17]
For some reason, I kept getting this error when I update your plugin.

`Failed to load resource: the server responded with a status of 404 ()`

I then uninstalled the plugin and tried reinstalling, then I received this error 

`Better Word Count: styles.css not found`

This is definitely a non-issue but I just thought I'd let you know 😊

<img width="246" alt="Screen Shot 2021-07-17 at 11 07 43 AM" src="https://user-images.githubusercontent.com/79069364/126043098-0a4fabd9-8cd8-4854-a2c8-96707bf81b7e.png">

**Comment by lukeleppan** [comment]
Hi thanks. This is normal, the plugin doesn't have any styling so when updating obsidian throws that error. Nothing to worry about. Thank you 😄

**Comment by chetachiezikeuzor** [comment]
Oh, sorry then! Just wanted to make sure.
