### ISSUE TITLE
semi space seprate character

### ISSUE THREAD

**Issue by GodFatherMK** [lukeleppan/better-word-count#19]
Thanks for the plugin.
It counts semi space as a seprate character in right to left languages. 
Example:

می‌باشد: is a one word in persian. but the pluging counts it as two word. It's beacause of semi space between می and باشد.

**Comment by lukeleppan** [comment]
Hi could you check if the count is same or different to the core word count plug-in? Thank you for the bug.

**Comment by GodFatherMK** [comment]
> Hi could you check if the count is same or different to the core word count plug-in? Thank you for the bug report.

Hi. Thanks for reply.

I checked it. the count is same to the core work count plugin. both plugin count semi space as a seprate word.

**Comment by lukeleppan** [comment]
This plugin tries to maintain the same word count plugin as the default. So if the default word count is count incorrectly please create a big report on the obsidian forums. When it is fixed, I will update. Sorry. I will keep this issue open until it the for the time being. Thank you.
