### ISSUE TITLE
Perf: Use `vault.cachedRead` instead of `read`

### ISSUE THREAD

**Issue by liamcain** [lukeleppan/better-word-count#2]
Hi, I noticed a couple of issues in regards to performance in your plugin. Hope you don't mind!

- `if ((file.basename = activeLeaf.getDisplayText())) {` This should probably be `===`.
- You're using vault.cachedRead in some spots, but not everywhere.
- The default wordcount plugin uses a background worker to calculate the word count. You might want to consider doing the same to avoid any performance lockups.
- Maybe instead of trigger an update every 500ms, just listen to the vault modify event?

**Comment by lukeleppan** [comment]
Thank you I appreciate the feedback.  
Could you please explain what you mean in your 3rd point?
Also would the vault modify event detect text selection? 
Again I appreciate the help.

**Comment by liamcain** [comment]
> Also would the vault modify event detect text selection?
For handling text selection, you mind need to listen to CodeMirrors `cursorActivity` event.

> Could you please explain what you mean in your 3rd point?

The app uses a background WebWorker so that the `read` isn't blocking the main thread. Unfortunately, there's nothing exposed in the app to reuse the existing webworkers but you could look into creating one yourself.

**Comment by lukeleppan** [comment]
Thank you I will see what I can do👍
