### ISSUE TITLE
Not working with multiple files open in preview

### ISSUE THREAD

**Issue by crissxross** [lukeleppan/better-word-count#20]
Using version 0.7.7
Default general & status bar settings
Obsidian v.0.12.11

When I have multiple files open in preview, the status bar word & character counts do not update when I change focus from one pane to another.

**Comment by lukeleppan** [comment]
Thank you of the bug report. I will look into it.

**Comment by Moonbase59** [comment]
Fine in edit, but not in preview mode, confirm that in 0.7.7 on Obsidian 0.12.12 (Linux).

**Comment by lukeleppan** [comment]
Yes it may not be fixable for the time being. Similar to issues with preview in #6.

**Comment by lukeleppan** [comment]
I think this issue has been resolved with the latest update. Please notify me if I'm wrong.
