### ISSUE TITLE
Total word count not always showing

### ISSUE THREAD

**Issue by phlind** [lukeleppan/better-word-count#24]
Hey, I have the issue that the total word count is not showing up when I'm in a normal Markdown note (then it just says "0" as the count). It does however show up when I'm not on a Markdown file, e.g. a Kanban board or a PDF, and the alternative status bar us used. 

I have the following settings:

Status Bar Text:
`{word_count} words ·
{total_word_count} total · 
{file_count} notes`

Alternative Status Bar Text:
`{total_word_count} total · {file_count} notes`

I deactivated "collect statistics" and activated "Don't count comments".

This is my .vault-stats file:

`{"2021-08-16":{"files":301,"modifiedFiles":{},"words":0,"characters":0,"sentences":0,"totalWords":61421,"totalCharacters":443368,"totalSentences":2843},"2021-08-17":{"files":301,"modifiedFiles":{},"words":0,"characters":0,"sentences":0,"totalWords":61325,"totalCharacters":442553,"totalSentences":2838},"2021-08-18":{"files":0,"modifiedFiles":{},"words":0,"characters":0,"sentences":0,"totalWords":0,"totalCharacters":0,"totalSentences":0},"2021-08-19":{"files":0,"modifiedFiles":{},"words":0,"characters":0,"sentences":0,"totalWords":0,"totalCharacters":0,"totalSentences":0},"2021-08-20":{"files":0,"modifiedFiles":{},"words":0,"characters":0,"sentences":0,"totalWords":0,"totalCharacters":0,"totalSentences":0},"2021-08-21":{"files":0,"modifiedFiles":{},"words":0,"characters":0,"sentences":0,"totalWords":0,"totalCharacters":0,"totalSentences":0}}`

**Comment by mm47** [comment]
I was having a similar problem but the "collect statistics" was on and the "Don't count comments" was off. I closed the app, deleted the .vault-stats file, opened the app, turned the "Don't count comments" on, reloaded the app and it worked.

**Comment by Kuiriel** [comment]
Where do you access these settings? It says highly customizable status bar , but I can't seem to figure out how to modify anything about it and don't know where you're changing those values.

**Comment by lukeleppan** [comment]
All these comments should be resolved in the latest update.
