### ISSUE TITLE
How to view day's word count in a daily note?

### ISSUE THREAD

**Issue by kenanmike** [lukeleppan/better-word-count#25]
Is it currently possible to view the day's word count inside a note rather than in the status bar only? For example, I'd like to have a section on each daily note which displays the words written that day, and then be able to look back on different day's notes and see the various word counts for each day.

**Comment by lukeleppan** [comment]
Yeah this is a feature that is on the list but first I'm working on a separate view that will let one see the notes stats and their vaults stats in the same place. The will be the next big feature aside from new metrics
