### ISSUE TITLE
Update fails to install

### ISSUE THREAD

**Issue by archelpeg** [lukeleppan/better-word-count#3]
In Obsidian 0.9.13 when I try to update the plugin from the community plugin page from version 0.3.0 to 0.3.2 it fails to update.

Looking at the console, clicking on update throws a 404 error, it doesn't find `manifest.json`.

In your releases on Github the newest version is 0.3.1

**Comment by lukeleppan** [comment]
Hmm... That's my bad. I will fix it now. Thank you for alerting me 👍

**Comment by lukeleppan** [comment]
Everything seems to be working now. Let me know if anything is still broke.
