### ISSUE TITLE
Cannot get plugin to work

### ISSUE THREAD

**Issue by menagerie198** [lukeleppan/better-word-count#33]
I am on 013.12 (installer 0.12.19). with BWC loaded and enabled (Obs core word count turned off) but nothing of BWC is showing up in the status bar. I have checked this with the help vault, and a vanilla test vault.

**Comment by aaylnx** [comment]
Same with me. I'm running 13.12 on Linux and BWC no longer works at all. I've disabled, uninstalled, and reinstalled several times, but that doesn't help. I also have turned off the core word count, but that doesn't seem to matter.  I thought that perhaps BWC would work with the public releases, but I tried a fresh install of 12.19 and it doesn't work on that either. I think it's just broken now. No updates in 5 months.

**Comment by tan-zx** [comment]
Probably not the solution you're looking for, but enabling the "Use legacy editor" option and it seems to work. Would require giving up Live Preview though.

**Comment by aaylnx** [comment]
> Probably not the solution you're looking for, but enabling the "Use legacy editor" option and it seems to work. Would require giving up Live Preview though.

Very interesting! I did not think about live preview breaking this, or any other plug-in, but I can see how this might have happened. Thanks!

**Comment by gchegr** [comment]
Same :(

**Comment by lukeleppan** [comment]
Hi everyone, happy holidays. Yeah it definitely looks like it is 100% broken with live preview. I will look into it today. Thanks for raising the issue!

**Comment by aaylnx** [comment]
> Hi everyone, happy holidays. Yeah it definitely looks like it is 100% broken with live preview. I will look into it today. Thanks for raising the issue!

Thank you!!!  Appreciate your work.

**Comment by nickmilo** [comment]
Yes, thank you for your work Luke. Any updates on the solution? (I feel your pain with maintaining a plugin/theme!)

**Comment by lukeleppan** [comment]
Hi everyone, thanks to all of you for reaching out and providing your input. I'm sorry it's taking a long time to be fixed. As I mentioned on another issue thread I'm currently in the middle of a move so my time with a computer is limited. I will keep you all updated.

**Comment by 5amcrawford** [comment]
It doesn't work for me either on mac.

**Comment by veradrawer** [comment]
I can confirm. This plugin currently only works with the Legacy Editor.

**Comment by physicshinzui** [comment]
I've confirmed the same problem with the current editor. But once I change it to the legacy one, it works fine.

**Comment by menagerie198** [comment]
Thanks Luke
