### ISSUE TITLE
Better Word Count Not Working in Live Preview

### ISSUE THREAD

**Issue by Craftidore** [lukeleppan/better-word-count#35]
# Better Word Count Not Working in Live Preview

**Steps to Reproduce**:

Download the latest build of obsidian, turn off safe mode then download and enable Better Word Count, enable live preview, and make a file. Better word count won't count the words in the file.

**Comment by olivia530** [comment]
Came here to post this same issue. Would love to see a fix for this, I love this plugin and make use of the selected word count on a daily basis!

**Comment by ReaderGuy42** [comment]
Same :)

**Comment by TheTRCG** [comment]
Same for me as well, temporary workaround for anyone who needs to use the tool is to revert to the legacy editor which is available in Settings>Editor>Legacy Editor

**Comment by nomad101** [comment]
> Same for me as well, temporary workaround for anyone who needs to use the tool is to revert to the legacy editor which is available in Settings>Editor>Legacy Editor

Thanks for indicating temporary fix. Like others, really would appreciate this working with the new Live Preview

**Comment by colintedford** [comment]
Also doesn't work in Source Mode. As pointed out, it only works in the Legacy Editor.

**Comment by L-Y-L** [comment]
Same，OB v0.13.18

**Comment by miles-zijingwu** [comment]
Same. It would be nice to get it fixed!

**Comment by koh-sy** [comment]
Same, v.0.13.19

**Comment by oldjove** [comment]
Same. v.0.13.21

**Comment by cuemix** [comment]
Same here, v.0.13.21

**Comment by 5amcrawford** [comment]
Not working for me either on mac.

**Comment by colintedford** [comment]
Here's a workaround for Mac (not tested there yet, but works on iOS/iPadOS): https://github.com/lukeleppan/better-word-count/issues/30#issuecomment-1025241909

(Or of course you can copy-paste to — or edit in — another app.)

**Comment by OnkelTem** [comment]
It's too bad that it doesn't work in the default editor. I personally can't go without Live Preview, it's the best which ever happened with Obsidian. I do can switch to the Source mode however, but not ready to disable Live Preview completely which requires Obsidian restart.

Please, make it work.

**Comment by lukeleppan** [comment]
Yeah as a student I've been struggling without it too. Sorry for the inconvenience everyone.
