### ISSUE TITLE
Feature request: Also count number of sentences (sentence count)

### ISSUE THREAD

**Issue by AngelusDomini** [lukeleppan/better-word-count#4]
I'm wondering if this feature request is doable. Would it be possible to also show the number of sentences present in a note as well as the number of sentences present under text selection? I've seen from the Extract Highlights plugin that you could use a hotkey to highlight a sentence without selecting, so I guess that means it's possible to detect sentences in text and thus be able to have a sentence count as well. Hope you'd consider this request, thanks :)

**Comment by lukeleppan** [comment]
Sorry for the late reply. Only got notified of this now. Thank you for the suggestion. It should be very doable. I will look into it as soon as I can. It'll probably be a toggleable feature.

**Comment by lukeleppan** [comment]
Sentence Count Added. Thank you for the suggestion.
