### ISSUE TITLE
Better Word Count not working in legacy editor

### ISSUE THREAD

**Issue by comradekade** [lukeleppan/better-word-count#40]
Hello, using version 0.13.23 and better word count stopped working. I've tried switching to the Legacy Editor but it still isn't working. Is there any other way or can I no longer use better word count? Thanks!

**Comment by olivia530** [comment]
Came here to post this—I accidentally updated to v0.8.1 before finding out it was no longer compatible with the legacy editor, which I use. I uninstalled the plugin, downloaded v0.8.0 and manually installed it. Won't work anymore.

**Comment by nomad101** [comment]
Yes, I was confused. With the latest version of Obsidian, does the older version of Better Word Count (0.7.7) not work even in legacy editor? Or do we need to run an older version of Obsidian too?

**Comment by lukeleppan** [comment]
Version 0.7.7 should work with the legacy editor. (Not 0.8.0)
