### ISSUE TITLE
Bug: Apostrophe issue not resolved?

### ISSUE THREAD

**Issue by icegrim** [lukeleppan/better-word-count#46]
Thanks for the plugin! I use it for the overall word count and the word count in the selected text. But I noticed that words with apostrophes continue to count as two words instead of one. They have fixed this problem in the core plugin. It would be great if you could fix it too. Thanks.

**Comment by icegrim** [comment]
#36 #37

**Comment by lukeleppan** [comment]
Looking into it.

**Comment by lukeleppan** [comment]
Closing this and using #54 as the update channel for the bug. Thank you everyone.
