### ISSUE TITLE
Bug - Can't find global file /word count

### ISSUE THREAD

**Issue by MosheSteinberg** [lukeleppan/better-word-count#49]
I can no longer find the global (vault-wide) file and word count, even when in graph view. I'm on the latest version of the plugin (0.8.1) and latest version of obsidian (0.14.15)

**Comment by ArtemisFowl-san** [comment]
I'm having the same problem

**Comment by ArtemisFowl-san** [comment]
Nvm, didn't read the readme file close enough, my bad

**Comment by Kuiriel** [comment]
> Nvm, didn't read the readme file close enough, my bad

I've read the readme and I still don't see how to see what the vault-wide word count is. I can see it per file only, and if I browse to a closed file / no file open, the bottom right counter just tells me the word count for the last file I was looking at.

It would be great to be able to choose to have a daily word count saved via this lovely program, as daily stats doesn't get the month right and seems to keep dropbox in a state of unable to update as the file is seemingly being constantly updated, even if there is nothing to add.

**Comment by lukeleppan** [comment]
I have good news in the latest update you can now customise a different alternative status bar for non-markdown files. Please enjoy and let me know if there are any further issues.

**Comment by MosheSteinberg** [comment]
The alternative status bar is giving me 0 for both words and files:
![image](https://user-images.githubusercontent.com/46159405/206898698-97ce47d6-09b9-4a9b-a837-5114d71cf93b.png)

**Comment by lukeleppan** [comment]
Yeah so I should have adequately mentioned that you need to have turned on collect stats otherwise
Only "current counts" counts will work because of the way it predicts the total count so it doesn't have to recount every key press.

**Comment by MosheSteinberg** [comment]
Ah, makes sense. Thanks!
