### ISSUE TITLE
Feature Request: Also Request File Count on Graph View

### ISSUE THREAD

**Issue by eleanorkonik** [lukeleppan/better-word-count#5]
Since the bar that displays wordcount is not terribly useful on graph view, it might be nice to get a total number of files, orphaned files, tags, etc. 

Thank you!

**Comment by lukeleppan** [comment]
Sorry for the late reply. Only got notified about this now. That is a very good idea. That way no space is wasted on the bottom bar. Thank you for the suggestion. I'll see what I can do as soon as possible.

**Comment by lukeleppan** [comment]
I have released the new feature. It was a needed one, I just didn't know I needed it. I'm closing this issue now but I will add more counts and customization over time. Thank you.
