### ISSUE TITLE
Global Stats Missing?

### ISSUE THREAD

**Issue by FrocketGaming** [lukeleppan/better-word-count#52]
The plugin says it offers stats for the entire vault but I've never seen those and have no idea where to find that data. When I close out a page and have no file open it doesn't show any stats at all.

**Comment by lukeleppan** [comment]
There was a notice on the readme explaining that the plug-in had to be rewritten. But today you can update to 0.9.0 and turn on stat collection. Please enjoy the plug-in and let me know if you have any further issues but I will close this now.
