### ISSUE TITLE
Different word counts for same note

### ISSUE THREAD

**Issue by giraffelionscarf** [lukeleppan/better-word-count#54]
Theres 2 detailed word counts at the bottom and they're both different. 

<img width="441" alt="Screenshot 2022-10-08 at 8 58 52 PM" src="https://user-images.githubusercontent.com/115362791/194715166-7515f0f3-6149-4d54-84f7-5616aee17d50.png">

**Comment by Trikzon** [comment]
I'm getting the same issue

**Comment by NolSet** [comment]
I've found the same issue, specifically looking at words using apostrophes. So using "you're" counts the same as "you are".
[Example issue.md](https://github.com/lukeleppan/better-word-count/files/10171062/Example.issue.md)

**Comment by NolSet** [comment]
@lukeleppan If you add in 
`\\'`
to line 17 (or 5, up to you really) in [StatUtils.ts](https://github.com/lukeleppan/better-word-count/blob/master/src/utils/StatUtils.ts) it should be a small workaround at least for counting words appropriately that are shortened. So it should read something along the lines of:
`(?:[0-9]+(?:(?:,|\\.)[0-9]+)*|[\\-\\'${spaceDelimitedChars}])+`,

Here's also a TS playground link so you can check it out in practice [Link](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAcwKZQOpwE4BMDCc4UAFFKgB5QBciAzlNjGMgJS1ggC2ARqtogDeAKESIICBvQAOAQwioAIqgA2MLjHIEAFrOx1EAXlFjEAegCCAWgBasqwC8AOiAAMrixZfuAQgFZvVx8vN1d8VytAxQA2KIAOSNCAMVjkhO8AJnwARkz8aMTXDMVctwyAUQjM8oAWavxq8u8AZgB2Krc2us7W1Nc21pbW6yHFIaSWuL7muPTOuJD+uIb58sLmi1L+i2b1pIDOpNbCmrit05G3PwyJq+bswr8-PqeATm9nh4+4wavFDtcfnKiz8SQBoIy3miGQB0Rqi2i0SabkRt1c0VaXxRimaUMUB3R5QJSL6SORhLR0SSl3RSRWtLRmNc3kxGUKrRuLJqinZFgJrR8W1a+BprWBLKS3VcrX2EsWcXchTOBLO8oyUriGTi3jiNQBcT82rcC31Pilr1cNUKr2a7zcNrG9r8zKdc1cr2iW1emOtCu8rwNvvpAbRrwt-pt1osRvdnmtPhd7p8kPtPgK-p8dqTjvd+HJr0UwcUOYLSWt5S9YP9SS2FkBhTrizraM2ic2u28Fi1nYyNJ2beaKY8zVxbh2BJ2fR2MZ2Wb5rwbfnpfPJFg5DdaUujfgbcRz0bLndetcjnejZ77Cc7yevo48-gbmev+-+ncqb9rSSzCZ33gT9ITNFBUTQUOzcZMY2TGkfGaEDBz-EcEN-cDbQQnN-AAvx0NBQo0y2HxMT-OI7x8QMiMWUi1j-cNwNeNlqIJTNv1eCjXgA15yUzICdj-CwpWCN1ggoiwqPAp9wNfNxwmQsIwm8cJRLCbJExyeipO7dSaXwVCpOaHN8ENQoDMWfIVM9eSyKk5YLMU-AaLCOijPPKS43kmC3Jk-BxLCHx9MUck8xUit5JrEKh3+GT-npf5FJKRMSjU1wcUWHEc0UGpyXxQ83BiLZFGGQp8rRRRLKSj1vEUFjCsFCqYOqnxarS8JCvybxKixVxylgtr4LcLq71qAFaj6cozjazVxqlUbfk62ZxsWUac3KV4rTa701oXNa0WBDrgQGvk2rXQ6FosBq+osHk2qvPqbxugbfLa5rHqm1q+sLQpykUNEwUTSUAUlGbJU2twUnpJJZkKcGVmUxUXGU3s4f6W5lOdRIUYOFHLhRx1lPMkBcYx9FUlx0TlPaRHWmQ5Sxvx1w4mRZS6zRsJCfwX5lPwHGko6ZTqURuk0fVI1snVLH1RxjJUbhyXicl4XJbFrDpeiHmtXlhZBb3aWLUF66ReTXWMYyUjdYZrIXRF-A1Mto38DmEWYmlkq0fuC37mt+4Mfue3mj8EJshmHmZmRjYg9lfHmnBl2khxvUsWyRFodRNGMWR6IzhTli4eiJns-FfGqXjqlhfaHn2mh9pScxUpsg5Mv7jhzcy78GvejL6IK6RNHWnJ-HWgVbv3L7-LG8LOHNR5n52dmSfnOyBZ-biBM0bicPsgtHnjwZ14pfxj0ce9TfNzhgNN9Ok-l5Puy4brHnNmJrs778bpsk8dmfzRmDR2yM0qbNM6f7EU-nWOGwQGbBGRj4YIn8iRw3CDzK2398DcjRsg5GxlUGtBxnmYG2Q8zQzzKTfAoV8bEIxsQ4m-weaKB8MjSoPMawYxrPbGsOMkgwjRpKJhpxOHcjhvsBhfh2b7DtNkfYAD9hsJwvwrB-CB78LNAo9M+Mkg+GhqohmdJrZ0hfnSZRYj8DqP+JwnE-CYgmIkZUTh5R1HsM4ZKfhKR7ErBhIREArjbgwh1i4LxLj4Y+LJgEjwiQMjZADgE7IBxQnrxCWEx0oT1QBIyKkBJRoEmXASfEkW2VQk6VyfgWJkcAk1GQqEmodoynIlCcRAJuofHwJCVbKp2kOhZCBPUlWjTaj1PKD4LpzT2H1KSKOYosN3GKElj4iZvxijFCmbBEJMQZkxE8SVVplUUmKFzuMiwmzoyLJElMy+4y0xHLmMUHwVTCzrNesUO2iy8xTOMU8zZzsnlVPKJyEAsFAQuB+akWC9xEiAoOICs6gKViu2Qu7R09wgV-Pnsie42z7jBARWCYFYjbjND1B0bk-gXC3w6HxayIA+LPLJTUGOhLnTEpVisXZylEiMtuLshGZLoRnV2XqZliJkS7JlLygshKc50tgWSzExxCWYlZRyNSa45oSqXsy4Yjo1zHPVb8NcRxmUKlKNGfourflkoVFKk1HhCUKgKZajIKZow8sta0Uc0ZNS6qHgeeVq8tWry5avNVFpLgWDogcINCzCUrVSEGzp4bhTht1My14t0g3EPDVY1N3Qg3lGUZm1lrxqQJqSPy2+zKuxGk8A6slfE7V8VWpWmoXLdnErXJGtcIQ36iU8BYVlp19WnRDadFtmYS0PUreEQlFgrbjpoSW4s4602Vvzp4Ox46HFkoTFiU66JCUJmBpu-lgoN2CkjcmYlyZj1amZcmfdYa11+23UuS90QQ0EVPZ8wlDSXD5R4iAfKxz8qvX-X0z9MozpfjGdSaIjpqTtESNSSqLhVHgYTKkVRAdYOCl+KhqDgpsqqI0nhy4qjmgoZgnMIjKwiPIlUXqBDZpSjUdHNR7o1HlGqJqiAVROJYOpQQ-iDoMdV68ccrxtmvGMVidA+UGDCGpPMak6x8odIEPsKxEkYZIQ1M1FU-sDTKRWMaOU1bWDdJMN0kI3SW4amJnGZHhxmO5nCxmBMKYRAAA6OgRBsAKAANwmAkGAKQYAEAAGU5AKGUGoDQWgsB4AMMYFzZg-mWixLBcq3z3SXXS3mpLmxgWuD5ulgWSW1MuAymMvN+IzDuc8z54QfnJBQEQEFsAoX5BKFUOoTQqBcAxdwHQAA8lAbQ-AjDOfMAAbSS1pvLaXUuZdS9ijwKX8shFgkVwrtwysdAq34AAuoIbIABfJzLmxDVZAF51Avn6sBca3IKA5BsBIEME11AAB3RAAAlVAyBygUGkCQMb42xtiAAAYkAAPzUHGxEV4u2ADUkPqBI4ADQAB8nBOFc6wGHVg4fw9YAAKjR5NpwkQnAAHIAAkgg6Bhfa5FrrOg9B0EO7t1g8PQco5B01kL9OIudeizgPr3PTu85a-zjrUXuu9YG0N-govTC7dcwAKzgMwEgAAiNHmvWCK7EJr5AmuTCsF82D-zHmVCoFcyoOAyASD3ce2Ac7l3WCg5MNgdAF2kBkEoFAVzXBZBQAgNoB3QenesEQGjtHiBxvs5t6gFgQ3fOHbqxbuAVubd25IGgTAwvCDEC1wAFW0DAAwDAmAsHEEQMAUADBQDgIgYAMAABu1vdesGEOnzPtv7e596wX2vxfS-l8YMwZAFOVAqEQLIFQHnEB8Cb639vrBWBAA)

**Comment by lukeleppan** [comment]
Yes thank you. Just merged #37 thank you.
