### ISSUE TITLE
Bug - Better Word Count does not show counts for text within Advanced Tables tables

### ISSUE THREAD

**Issue by Ste-Bergin** [lukeleppan/better-word-count#59]
Better Word Count can usually show backlink count, word count, and character count for the whole of a document, or for a portion of a document that has been highlighted.

When I highlight text that is in a table created with the Advanced Tables plugin by Tony Grosinger, Better Word Count continues to show the backlink count, word count, and character count for the whole of the document. Once you go into the table into the traditional markdown view, then you can highlight the text and Better Word Count works correctly.
![Screenshot (78)](https://user-images.githubusercontent.com/80220097/206248391-f5981ad6-048b-492f-8bc2-f301eebf88b7.png)
![Screenshot (77)](https://user-images.githubusercontent.com/80220097/206248398-c4d49523-4d89-40d9-9f6a-2ed42b241daf.png)

**Comment by lukeleppan** [comment]
I'm not sure if there is a solution for this but will leave this open for now. And keep you informed

**Comment by lukeleppan** [comment]
Ok so the plugin is only able to access the text that is saved to your computer, the table is being rendered separately and so the plugin can't detect when text is highlighted in the rendered table. So this issue cannot be resolved.
