### ISSUE TITLE
Wordcount Inaccurate for Preview 

### ISSUE THREAD

**Issue by eleanorkonik** [lukeleppan/better-word-count#6]
If I embed a bunch of prose files into one file and then try to look at the preview, the wordcount will show as something tiny like 27 words even though there are several thousand words actually on the screen. Is it possible to fix this so that the wordcount is accurate for preview instead of pulling only from the raw markdown on edit view?

**Comment by lukeleppan** [comment]
Sorry for the late reply. Only got notified of this now. I recall getting issues with the preview view. For instance, the highlighted text in preview can't be counted. However I will see what I can do about fixing the full word count. Thank you.

**Comment by Cmhorn** [comment]
This is needed to resolve the issue of how to accurately not count formatting text, or to count accurately text which is a combination of note text and transcluded text from another note.

**Comment by davidrsim-p** [comment]
Just a +1 for this. I'm increasingly using transclusions to make long documents easier to manage and to reuse recurring blocks, but I have to manually count each referenced block/file. If the plugin could count the words shown in preview that would resolve the issue completely. 

Thanks for a great plugin!

**Comment by lukeleppan** [comment]
Probably fixed in the latest update
