### ISSUE TITLE
regression: word count of selection in vim mode

### ISSUE THREAD

**Issue by 7596ff** [lukeleppan/better-word-count#60]
I use this plugin over the default because it would count the words I have selected. The latest version no longer has this capability, compared to 0.8.1.

**Comment by lukeleppan** [comment]
Hmmm it should still be working.

**Comment by lukeleppan** [comment]
Have you disabled the default word count?

**Comment by 7596ff** [comment]
Ah, I see what happened. It works with regular selecting, but using any kind of visual mode selection with vim mode doesn't.

**Comment by 7596ff** [comment]
https://user-images.githubusercontent.com/1760581/206879602-81479775-0b2b-4fd7-a49f-79fda8dd41d9.mov

**Comment by lukeleppan** [comment]
Ok and you say it worked before. This might be because it's only checking for selection using a mouse. Vim selecting might be labelled differently. Thanks for raising this issue I will keep you updated.

**Comment by ryanwwest** [comment]
I've observed the same behavior. I also had to reset the plugin and change note panes to get it to start working after a restart, though that's probably related to needing to rework live preview mode.

**Comment by 7596ff** [comment]
This seems to be fixed with the latest update (0.9.6). Thank you very much!
