### ISSUE TITLE
[Feature Request] Not counting comments with %%

### ISSUE THREAD

**Issue by nomad101** [lukeleppan/better-word-count#61]
Hello, thanks for updating this plugin!

I have the option 'Don't Count Comments' on, but  comments in a file are still being counted if I use the %% ... %% to wrap text with.  If I use `<!-- ... -->` it works as expected. 

As far as I understand, Obsidian [markdown](https://help.obsidian.md/How+to/Format+your+notes) recognises %% 

Using %% in-line is neater, and doesn't interfere with reading the text compared to <!-- 
Would you please consider updating the plugin?

Many thanks

**Comment by lukeleppan** [comment]
Hi thank you for notifying me. It looks like I forgot to make that setting do anything. I am currently reworking metrics and how they can be stored and displayed. I will then work on sanitisation options like this one which will apply to all the metrics. I will keep you informed as progress progresses.

**Comment by ReaderGuy42** [comment]
This would be cool :)

**Comment by Gewerd-Strauss** [comment]
I've been taking a look as well so far, but I haven't found a suitable needle for this yet, unfortunately. 

I figured how to remove html comments properly: `/(?=<!--)([\s\S]*?)-->/g`, using the modified `getCharacterCount()` I proposed in [my comment in 48](https://github.com/lukeleppan/better-word-count/issues/48#issuecomment-1406287167). 

Maybee I'll try and find a suitable needle in the coming days, but as I don't ever used `%%`-comments, I might not do so anyways.

**Comment by nomad101** [comment]
Thanks for looking into this. I appreciate you have limited time. (If I could code, I'd try myself).

If its any help, the [dataview plugin](https://github.com/blacksmithgu/obsidian-dataview) doesn't count words wrapped with %%. (But otherwise it's overkill).

**Comment by lukeleppan** [comment]
Not counting comments, has been thrown back in.

**Comment by ReaderGuy42** [comment]
Great, thank you! Quick question, what does the `!!!` indicate when you hover over the status bar?

**Comment by nicolascoffman** [comment]
I see this has been marked as completed, but I'm having issues with %% still being counted.  Should I be looking for a different fix?
