### ISSUE TITLE
[Feature Request] Functions and Statistics accessible by other plugins like dataview

### ISSUE THREAD

**Issue by xDovos** [lukeleppan/better-word-count#62]
Hello, 
i don't know how hard my request is but it would be great if there could be a small API that let's me use funtions like getWordCount(text) directly inside dataviewjs by loading the api with 
const bwc = app.plugins.plugins["better-word-count"].api 
so that we can use these functions on our tables and get the separate word counts of the files or lists.
it would also be good if we can access the vault statistics it is collecting that way. by now i haven't found a way to load them without directly using JSON methods. (or i just haven't found where it is loaded inside obsidian, if it get's loaded somewhere)
thanks for listening and i hope it isn't too hard to do. (i really have no idea how much work or how feasible it is)

**Comment by lukeleppan** [comment]
Thank you, this is a great idea. I've seen it done in other plugins. I'll definitely add this to the list.

**Comment by thrly** [comment]
I would love this feature.
+1 to this request.

**Comment by chiusuan** [comment]
I need this function
