### ISSUE TITLE
Better Word Count obscures cursor while typing low on screen. Occurs with resized screen, not full screen.

### ISSUE THREAD

**Issue by JordanChoe** [lukeleppan/better-word-count#75]
When I have my Obsidian resized vs full screen and am typing in a note, as the lines and cursor move down, the typing and cursor are obscured by the BWC information in the lower status bar.  The only way to see this information is either carriage returns or using full screen. 

![image](https://user-images.githubusercontent.com/108248499/215915424-b62d3fd8-856b-463a-bba2-84db5297493a.png)
![image](https://user-images.githubusercontent.com/108248499/215915550-ccd766d6-f671-42b5-a2a0-81a55fdeedb6.png)
![image](https://user-images.githubusercontent.com/108248499/215915635-62cef28f-f199-47d6-a316-4552262d715f.png)

I did install today's update, closed Obsidian, reopened, and this persists. 

I have considered whether this might be an Obsidian issue vs plugin issue.  It is likely an Obsidian issue as it persists with plugin turned off. However, I did also want to make you aware if others post about this issue.

**Comment by kometenstaub** [comment]
That's an Obsidian issue that should be fixed in recent versions.

**Comment by lukeleppan** [comment]
Thank you @JordanChoe but this is/was an obsidian issue. Closing this please reopen if I'm wrong.
